# Setup
title: Home
tagline: ''
description: 'This text can be edited in config.yml'
url: 'https://siegfriedfabian.github.io'
baseurl: ''

# Pagination
paginate: 5
paginate_path: "/page:num/"  # Note the added slash

# Build settings
markdown: kramdown  # Added this
highlighter: rouge  # Added this

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist     # Added this
  - jekyll-seo-tag  # Added this

# Permalinks
permalink: pretty

# About/contact
author:
  name: Fabian Lander      # Fixed indentation
  email: landerfabian at gmail dot com

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y