title: "Fabian Lander - Mathematics"
description: "PhD Student in Geometry, Groups and Dynamics at Max Planck Institute for Mathematics. Research on straight line flows on half-dilation surfaces."
url: 'https://siegfriedfabian.github.io'
author:
  name: Fabian Lander
  email: landerfabian at gmail dot com

# Pagination
paginate: 5
paginate_path: "/page:num/"  # Note the added slash

# Build settings
markdown: kramdown  # Added this
highlighter: rouge  # Added this

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist     # Added this
  - jekyll-seo-tag  # Added this

# Permalinks
permalink: pretty

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y