# Setup
title: Lanyon
tagline: 'A Jekyll theme'
description: 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url: 'https://siegfriedfabian.github.io'
baseurl: ''

# Pagination
paginate: 5
paginate_path: "/page:num/"  # Note the added slash

# Build settings
markdown: kramdown  # Added this
highlighter: rouge  # Added this

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist     # Added this
  - jekyll-seo-tag  # Added this

# Permalinks
permalink: pretty

# About/contact
author:
  name: Mark Otto      # Fixed indentation
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y